name = "tedxiceas-2026-website"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB"
database_name = "tedxiceas-db"
database_id = "e8911620-331c-4a0c-907f-d133c07e0a3e"
migrations_dir = "drizzle"
[[r2_buckets]]
binding = "R2"
bucket_name = "tedx-iceas-2026-media"
